"""The experiment grid: every setup the project compares, defined once.

Thirty setups: three chunkers, five first-stage retrievers, and each of those with and without the
reranker. The config files are generated from this one definition and committed, so no setup can
differ from the others by a typo, and a test fails if a committed file drifts from it (decision
50). Everything a setup does not vary is shared: the same corpus, seed, chunk size, BM25
parameters, fusion constant and cutoffs.
"""

import logging
from dataclasses import dataclass
from pathlib import Path

from groundwork.chunking import ChunkStrategy

logger = logging.getLogger(__name__)

SEED = 1
CHUNK_SIZE = 150
CHUNK_OVERLAP = 30
DEPTH = 100
CUTOFFS = (1, 5, 10, 100)
BM25_K1 = 0.9
BM25_B = 0.4
FUSION_K = 60
FUSION_CANDIDATES = 100
RERANKER = "bge-reranker-v2-m3"
RERANK_DEPTH = 50

_CHUNKERS: dict[str, tuple[ChunkStrategy, str]] = {
    "fixed": ("fixed_words", "fixed-size word chunks"),
    "sentence": ("sentence_aware", "sentence-aware chunks"),
    "section": ("section_aware", "section-aware chunks"),
}

_EMBEDDERS = {"minilm": "all-MiniLM-L6-v2", "qwen3": "Qwen3-Embedding-0.6B"}


@dataclass(frozen=True, slots=True, kw_only=True)
class Setup:
    """One cell of the grid.

    Attributes:
        chunker: Short chunker name, as used in the setup name.
        retriever: bm25, minilm, qwen3, hybrid-minilm or hybrid-qwen3.
        rerank: Whether the reranker re-orders the top of the first-stage ranking.
        flatten_tables: The table ablation: tables chunked as loose text.
    """

    chunker: str
    retriever: str
    rerank: bool
    flatten_tables: bool = False

    @property
    def name(self) -> str:
        """The setup's name, which is also its results directory."""
        parts = [self.chunker, self.retriever]
        if self.rerank:
            parts.append("rerank")
        if self.flatten_tables:
            parts.append("flat-tables")
        return "-".join(parts)


def grid() -> tuple[Setup, ...]:
    """Return every setup in the grid, in a fixed order."""
    retrievers = ("bm25", *_EMBEDDERS, *(f"hybrid-{key}" for key in _EMBEDDERS))
    return tuple(
        Setup(chunker=chunker, retriever=retriever, rerank=rerank)
        for chunker in _CHUNKERS
        for retriever in retrievers
        for rerank in (False, True)
    )


def render(setup: Setup) -> str:
    """Return the TOML config for one setup.

    Raises:
        ValueError: If the setup names an unknown chunker or retriever.
    """
    if setup.chunker not in _CHUNKERS:
        raise ValueError(f"unknown chunker {setup.chunker!r}")
    strategy, chunk_words = _CHUNKERS[setup.chunker]
    method, embedder = _retrieval(setup.retriever)

    lines = [
        "# Generated by `groundwork grid` from src/groundwork/grid.py; edit that, not this file.",
        "",
        f'name = "{setup.name}"',
        f'description = "{_describe(setup, chunk_words)}"',
        f"seed = {SEED}",
        "",
        "[corpus]",
        'name = "natural-questions"',
        'split = "validation"',
        "",
        "[chunking]",
        f'strategy = "{strategy}"',
        f"size = {CHUNK_SIZE}",
        f"overlap = {CHUNK_OVERLAP}",
    ]
    if setup.flatten_tables:
        lines.append("flatten_tables = true")
    lines += ["", "[retrieval]", f'method = "{method}"', f"depth = {DEPTH}"]
    if method in {"bm25", "hybrid"}:
        lines += [
            "",
            "[retrieval.bm25]",
            f"k1 = {BM25_K1}",
            f"b = {BM25_B}",
            "stem = true",
        ]
    if embedder is not None:
        lines += ["", "[retrieval.dense]", f'model = "{embedder}"']
    if method == "hybrid":
        lines += [
            "",
            "[retrieval.fusion]",
            f"k = {FUSION_K}",
            f"candidates = {FUSION_CANDIDATES}",
        ]
    if setup.rerank:
        lines += ["", "[rerank]", f'model = "{RERANKER}"', f"depth = {RERANK_DEPTH}"]
    lines += ["", "[evaluation]", f"cutoffs = [{', '.join(str(k) for k in CUTOFFS)}]", ""]
    return "\n".join(lines)


def write_grid(directory: Path) -> tuple[Path, ...]:
    """Write every setup's config into directory, removing configs no longer in the grid.

    Returns:
        The written paths, in grid order.
    """
    directory.mkdir(parents=True, exist_ok=True)
    setups = grid()
    wanted = {f"{setup.name}.toml" for setup in setups}
    for stale in sorted(directory.glob("*.toml")):
        if stale.name not in wanted:
            stale.unlink()
            logger.info("removed config no longer in the grid", extra={"path": str(stale)})
    paths = []
    for setup in setups:
        path = directory / f"{setup.name}.toml"
        path.write_text(render(setup), encoding="utf-8")
        paths.append(path)
    logger.info("grid written", extra={"configs": len(paths), "directory": str(directory)})
    return tuple(paths)


def table_ablation(name: str) -> Setup:
    """The grid setup with this name, with its tables flattened into loose text (decision 40).

    Raises:
        ValueError: If no grid setup has this name.
    """
    for setup in grid():
        if setup.name == name:
            return Setup(
                chunker=setup.chunker,
                retriever=setup.retriever,
                rerank=setup.rerank,
                flatten_tables=True,
            )
    raise ValueError(f"no grid setup is named {name!r}")


def write_table_ablation(name: str, directory: Path) -> Path:
    """Write the table ablation's config for a grid setup and return its path."""
    setup = table_ablation(name)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{setup.name}.toml"
    path.write_text(render(setup), encoding="utf-8")
    logger.info("table ablation written", extra={"path": str(path)})
    return path


def _retrieval(retriever: str) -> tuple[str, str | None]:
    if retriever == "bm25":
        return "bm25", None
    if retriever in _EMBEDDERS:
        return "dense", _EMBEDDERS[retriever]
    key = retriever.removeprefix("hybrid-")
    if retriever.startswith("hybrid-") and key in _EMBEDDERS:
        return "hybrid", _EMBEDDERS[key]
    raise ValueError(f"unknown retriever {retriever!r}")


def _describe(setup: Setup, chunk_words: str) -> str:
    method, embedder = _retrieval(setup.retriever)
    first_stage = {
        "bm25": "BM25 with stemming",
        "dense": f"{embedder} embeddings",
        "hybrid": f"BM25 and {embedder} fused by reciprocal rank",
    }[method]
    text = f"{first_stage} over {chunk_words}"
    if setup.flatten_tables:
        text += " with tables flattened to loose text"
    if setup.rerank:
        text += f", top {RERANK_DEPTH} reranked by {RERANKER}"
    return text + "."
